version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports: 
      - "27017:27017"
    volumes:
      - ./volumes/mongo-db:/mongo-bd-web-2/
      #- ./volumes/mongo-exprt:/data/db 