version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: host-mongo
    ports: 
      - "27017:27017"
    volumes:
      - ./volumes/mongo-db:/mongo-bd-web-2/
      #- ./volumes/mongo-exprt:/data/db
  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: expresMongo
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongo'
      ME_CONFIG_MONGODB_PORT: '27017'
    links:
      - mongo    
    ports:
      - "8081:8081"
